name: Bug Report / Feature Request
description: Use this form to report an installation/usage problem or request a new feature.
title: "[Bug/Feature]: "
labels: []
assignees: []

body:
  - type: dropdown
    id: issue_type
    attributes:
      label: "What type of issue are you reporting?"
      description: "Please select the category that best describes your issue."
      options:
        - Installation Problem
        - Usage Problem
        - Feature Request
        - Other
    validations:
      required: true

  - type: textarea
    id: error_message
    attributes:
      label: "Error Message (if applicable)"
      description: "Paste the error message here. If possible, wrap it in a code block with bash syntax (using triple backticks) for readability."
      placeholder: |
        ```bash
        # Paste your error message here...
        ```
    validations:
      required: false

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior / Feature Request Details"
      description: "Describe what you expected to happen or detail the new feature you are suggesting."
      placeholder: "Provide details here..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce (if applicable)"
      description: "If this is a bug report, please list the steps you took to encounter the issue."
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here (e.g., screenshots, system information, etc.)."
      placeholder: "Enter additional details here..."
    validations:
      required: false
